/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dc.avalon_client.Views;

import com.dc.avalon_client.FileHandler.Archive;
import com.dc.avalon_client.FileHandler.Field;
import com.dc.avalon_client.FileHandler.Handler;
import com.dc.avalon_client.IO.Reader;
import java.awt.Toolkit;
import java.io.File;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JFileChooser;

/**
 *
 * @author lucas
 */
public class MainFrame extends javax.swing.JFrame
{
    private Handler handler;
    /**
     * Creates new form MainFrame
     */
    public MainFrame()
    {      
        this.handler = new Handler();
        Archive archive = new Archive("TESTE_ID");
        this.handler.setArchive(archive);
        
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(MainFrame.class.getClassLoader().getResource("avalon_logo.png")));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnSelectFile = new javax.swing.JButton();
        btnDefineOperations = new javax.swing.JButton();
        btnDefineOptions = new javax.swing.JButton();
        btnExecute = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Avalon");
        setResizable(false);

        btnSelectFile.setText("Selecionar Arquivo");
        btnSelectFile.setName("btnSelectFile"); // NOI18N
        btnSelectFile.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSelectFileActionPerformed(evt);
            }
        });

        btnDefineOperations.setText("Definir operações");
        btnDefineOperations.setName("btnDefineOperations"); // NOI18N
        btnDefineOperations.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDefineOperationsActionPerformed(evt);
            }
        });

        btnDefineOptions.setText("Definir Opções");
        btnDefineOptions.setToolTipText("");
        btnDefineOptions.setName("btnDefineOptions"); // NOI18N
        btnDefineOptions.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDefineOptionsActionPerformed(evt);
            }
        });

        btnExecute.setText("Executar");
        btnExecute.setName("btnExecute"); // NOI18N
        btnExecute.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnExecuteActionPerformed(evt);
            }
        });

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Abrir arquivo");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Abrir Operações");
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setText("Sair");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExecute, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSelectFile, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnDefineOperations, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnDefineOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelectFile, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDefineOperations, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDefineOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnExecute, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDefineOperationsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDefineOperationsActionPerformed
    {//GEN-HEADEREND:event_btnDefineOperationsActionPerformed
        DefineOperations defineOperationsFrame = new DefineOperations(this.handler);        
        defineOperationsFrame.setVisible(true);        
    }//GEN-LAST:event_btnDefineOperationsActionPerformed

    private void btnExecuteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnExecuteActionPerformed
    {//GEN-HEADEREND:event_btnExecuteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExecuteActionPerformed

    private void btnDefineOptionsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDefineOptionsActionPerformed
    {//GEN-HEADEREND:event_btnDefineOptionsActionPerformed
        new DefineOptions().setVisible(true);
    }//GEN-LAST:event_btnDefineOptionsActionPerformed

    private void btnSelectFileActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSelectFileActionPerformed
    {//GEN-HEADEREND:event_btnSelectFileActionPerformed
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(this);
        
        if(returnVal == JFileChooser.APPROVE_OPTION){
            File myFile = chooser.getSelectedFile();
            String name = myFile + "";
            System.out.println(name);
            
            Archive arc = this.handler.getArchive();            
            arc.setFile(myFile);                        
            arc.setHeader(this.handler.getHeader(new Reader(name)));
                                              
            for (Iterator it = arc.getHeader().getFields().entrySet().iterator(); it.hasNext();) {
                Map.Entry<String, Field> entry = (Map.Entry<String, Field>) it.next();
                
                System.out.println("Key" + entry.getKey() + " / Value:" + entry.getValue().getName());
            }
        }
        
    }//GEN-LAST:event_btnSelectFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDefineOperations;
    private javax.swing.JButton btnDefineOptions;
    private javax.swing.JButton btnExecute;
    private javax.swing.JButton btnSelectFile;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
